export const DRAWINGS = [
  { id: "kyodo-7", name: "竣工図-7", file: "/drawings/kyodo-7.pdf" },
  { id: "kyodo-8", name: "竣工図-8", file: "/drawings/kyodo-8.pdf" },
  { id: "kyodo-9", name: "竣工図-9", file: "/drawings/kyodo-9.pdf" },
  { id: "kyodo-17", name: "竣工図-17", file: "/drawings/kyodo-17.pdf" },
];

export const EQUIPMENT = {
  washer: {
    label: "洗濯機",
    category: "機器",
    w: 70,
    h: 75,
    fill: "#dbeafe",
    stroke: "#2563eb",
  },
  dryer: {
    label: "乾燥機",
    category: "機器",
    w: 70,
    h: 75,
    fill: "#fef3c7",
    stroke: "#d97706",
  },
  combo: {
    label: "洗乾一体",
    category: "機器",
    w: 70,
    h: 80,
    fill: "#e0e7ff",
    stroke: "#4f46e5",
  },
  sink: {
    label: "シンク",
    category: "設備",
    w: 90,
    h: 55,
    fill: "#cffafe",
    stroke: "#0891b2",
  },
  counter: {
    label: "作業台",
    category: "什器",
    w: 120,
    h: 60,
    fill: "#f3f4f6",
    stroke: "#6b7280",
  },
  shelf: {
    label: "棚",
    category: "什器",
    w: 100,
    h: 35,
    fill: "#fef9c3",
    stroke: "#ca8a04",
  },
  table: {
    label: "テーブル",
    category: "什器",
    w: 90,
    h: 90,
    fill: "#fce7f3",
    stroke: "#db2777",
  },
  chair: {
    label: "椅子",
    category: "什器",
    w: 45,
    h: 45,
    fill: "#f3e8ff",
    stroke: "#9333ea",
    round: true,
  },
  partition: {
    label: "区画・壁",
    category: "構造",
    w: 140,
    h: 12,
    fill: "#374151",
    stroke: "#111827",
  },
  remove: {
    label: "撤去",
    category: "マーク",
    w: 50,
    h: 50,
    fill: "rgba(220,38,38,0.15)",
    stroke: "#dc2626",
    mark: "✕",
  },
  keep: {
    label: "残す",
    category: "マーク",
    w: 50,
    h: 50,
    fill: "rgba(22,163,74,0.15)",
    stroke: "#16a34a",
    mark: "○",
  },
  note: {
    label: "メモ",
    category: "マーク",
    w: 100,
    h: 50,
    fill: "#fffbeb",
    stroke: "#f59e0b",
    editable: true,
  },
};

export const STORAGE_PREFIX = "renewal-studio-";
